'use strict';
const groups=[['個性',['你覺得自己是個怎麼樣子的人？','你的朋友覺得你是個怎麼樣的人？','別人常會如何稱讚你？稱讚你的那個部分？']],['興趣',['現在的你最喜歡什麼？','這個東西最吸引你的是什麼？','是什麼經驗讓你覺得喜歡（過去、現在、未來）？','還有什麼是你喜歡的？','這些吸引你的東西有什麼共同或不同的地方？']],['價值',['對於找一份工作你在乎的是……','是什麼原因讓你覺得這是重要的？']],['能力',['你最在行的是什麼事？']],['感受',['整體而言，你對自己的瞭解是這樣子，你有什麼感覺？']]];
const traits=[
['薪水',['高','低'],'這份工作可以獲得比一般人高或低的薪水。',['薪水高','薪水低']],
['體力',['耗','不耗'],'工作時必須付出較多或少的體力或勞力，付出較多的勞力會比較辛苦，較少的勞力則比較輕鬆。',['耗體力','不耗體力']],
['高學歷',['需要','不需要'],'做這份工作必需或不需要取得較高的學位，如大學畢業。',['需要高學歷','不需要高學歷']],
['口才',['好','不好'],'這份工作需要或不需要有好的口才與表達能力。',['口才好','口才不好']],
['安全性',['高','低'],'工作內容或工作場所的危險性低或高。',['安全性高','安全性低']],
['環境',['乾淨','髒亂'],'工作地點的環境是乾淨或髒亂。',['環境乾淨','環境髒亂']],
['工作場所',['有','無'],'必須待在固定的地點工作，或可能會變換工作場所。',['工作場所有變化','工作場所無變化'],'變化'],
['室',['內','外'],'工作時會有較多的時間在室內或室外。',['室內','室外']],
['與人接觸',['多','少'],'工作時只接觸有限的幾個人或必須常常接觸不同的人。',['與人接觸多','與人接觸少']],
['為人服務',['是','不是'],'工作的主要內容是或不是在服務別人、幫助別人。',['是為人服務','不是為人服務']],
['動腦筋思考',['要','不要'],'工作時需要或不需要常常動腦筋思考以解決工作上的問題。',['要動腦筋思考','不要動腦筋思考']],
['工作',['自由','不自由'],'在工作中有較多自由、較少限制，可以自己選擇上班時間或做事的方式；或者受到的限制較多，必須依照公司的規定做事與上班。',['工作自由','工作不自由']],
['性別限制',['多','少'],'這份工作的性別限制多，只限男生或女生適合去做；或甚至少，男女生都可以做。',['性別限制多','性別限制少']],
['專業技術',['需要','不需要'],'需要或不需要有專業技術來完成這份工作。',['需要專業技術','不需要專業技術']],
['執照',['需要','不需要'],'應徵此工作時需要或不需要有與該工作有關的執照。',['需要執照','不需要執照']],
['工作時間',['長','短'],'花在這份工作上的時間較長或短。',['工作時間長','工作時間短']],
['工作時間',['規律','不規律'],'這份工作能不能有規律的工作或生活作息時間。',['工作時間規律','工作時間不規律']],
['福利',['好','不好'],'這份工作的福利，如加薪、休假、退休保障較好或不好。',['福利好','福利不好']],
['不斷學習',['需要','不需要'],'這份工作需要或不需要不斷的進修或學習新知識。',['需要不斷學習','不需要不斷學習']],
['自己喜歡',['是','不是'],'這份工作是或不是自己喜歡做的。',['是自己喜歡','不是自己喜歡']],
['耐心',['需要','不需要'],'工作時需要或不需要有較多的耐心。',['需要耐心','不需要耐心']],
['壓力',['大','小'],'工作中要面對的心理壓力或工作壓力較大或小。',['壓力大','壓力小']],
['權力',['大','小'],'工作時能有較大或小的權力。',['權力大','權力小']],
['被人管理',['是','不是'],'在這份工作中的職位可以管理別人或被別人管。',['是被人管理','不是被人管理']],
['挑戰性',['高','低'],'這份工作會有較高或低的挑戰性。',['挑戰性高','挑戰性低']],
['生活',['多樣','嚴謹'],'這份工作能使生活內容較多樣活潑或是比較嚴肅。',['生活多樣','生活嚴謹']],
['公平性',['需要','不需要'],'這份工作可以或不可以維持公平正義、伸張公理。',['需要公平性','不需要公平性']]
];
const fresh=()=>({answers:Array(12).fill(''),jobs:Array(10).fill(''),ranks:Array(10).fill(''),selected:[],poles:{},importance:{},ratings:{},identity:{},step:0});
let state=fresh();try{const loaded=JSON.parse(localStorage.getItem('career-grid-v1'));if(loaded&&Array.isArray(loaded.answers)&&Array.isArray(loaded.jobs))state={...state,...loaded}}catch{}
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('career-grid-v1',JSON.stringify(state));$('#save').textContent='已暫存於此瀏覽器'}catch{$('#save').textContent='無法暫存，請在離開前列印保存'}updateProgress()}
function updateProgress(){$('#progress').textContent=`自我訪談 ${state.answers.filter(x=>x.trim()).length}/12　想法 ${state.selected.length}/10`}
function showStep(n){if(!Number.isInteger(n)||n<0||n>2)throw Error('步驟必須為 0、1 或 2');state.step=n;['interview','grid','menu'].forEach((id,i)=>$('#'+id).hidden=i!==n);document.querySelectorAll('nav button').forEach((b,i)=>i===n?b.setAttribute('aria-current','step'):b.removeAttribute('aria-current'));if(n===1){renderGrid();renderGuided()}if(n===0)renderInterview();save();window.scrollTo({top:0,behavior:'smooth'})}
let q=0;$('#questions').innerHTML=groups.map(([title,qs])=>`<div class="question-group"><h2>${title}</h2>${qs.map(t=>{let i=q++;return `<label class="question"><span>${t}</span><textarea data-answer="${i}" aria-label="${t}">${esc(state.answers[i])}</textarea></label>`}).join('')}</div>`).join('');
$('#questions').addEventListener('input',e=>{if(e.target.dataset.answer!==undefined){state.answers[+e.target.dataset.answer]=e.target.value;save()}});
$('#identity').innerHTML=['學校','姓名','學號','班級','年級'].map(k=>`<label>${k}：<input data-identity="${k}" value="${esc(state.identity[k])}" aria-label="${k}"></label>`).join('')+`<label>性別：<select data-identity="性別" aria-label="性別"><option value="">未填</option>${['男','女'].map(k=>`<option ${state.identity['性別']===k?'selected':''}>${k}</option>`).join('')}</select></label>`;
$('#identity').addEventListener('input',e=>{if(e.target.dataset.identity){state.identity[e.target.dataset.identity]=e.target.value;save()}});
function renderChoices(){ $('#choices').innerHTML=traits.map((t,i)=>`<div class="choice"><input type="checkbox" class="tick" data-select="${i}" aria-label="選擇${t[0]}${i===15?'長短':i===16?'規律':''}" ${state.selected.includes(i)?'checked':''}><div><span class="choice-name">${t[0]}</span>（${t[1].map((p,j)=>`<label class="pole"><input type="radio" name="pole${i}" data-pole="${i}" value="${j}" ${state.poles[i]===j?'checked':''} aria-label="${t[0]}${p}"><span>${p}</span></label>`).join('、')}）${t[4]||''}：${t[2]}</div></div>`).join('');updateSelection() }
function updateSelection(){$('#selectedCount').textContent=`已選 ${state.selected.length} / 10 項`;const missing=state.selected.filter(i=>state.poles[i]===undefined).length;$('#selectionNote').textContent=missing?`還有 ${missing} 項尚未圈選特性`:state.selected.length===10?'已選好，可回到生涯方格排序與評分。':'請選出十項，並圈選您喜歡的特性。'}
$('#choices').addEventListener('change',e=>{const el=e.target;if(el.dataset.select!==undefined){const i=+el.dataset.select;if(el.checked){if(state.selected.length>=10){el.checked=false;$('#selectionNote').textContent='已選十項，請先取消一項再更換。';return}state.selected.push(i);state.selected.sort((a,b)=>a-b)}else{state.selected=state.selected.filter(x=>x!==i);delete state.importance[i];delete state.ratings[i]}renderChoices()}else if(el.dataset.pole!==undefined){const i=+el.dataset.pole;const next=+el.value;if(!state.selected.includes(i)){if(state.selected.length>=10){renderChoices();$('#selectionNote').textContent='已選十項，請先取消一項再更換。';return}state.selected.push(i);state.selected.sort((a,b)=>a-b);$('#choices [data-select="'+i+'"]').checked=true;}if(state.poles[i]!==undefined&&state.poles[i]!==next){delete state.ratings[i]}state.poles[i]=next;updateSelection()}save()});
function options(n,value){return '<option value=""></option>'+Array.from({length:n},(_,i)=>`<option value="${i+1}" ${String(value)===String(i+1)?'selected':''}>${i+1}</option>`).join('')}
const order=[9,8,7,6,5,4,3,2,1,0,10];
function traitLabel(i){return state.poles[i]===undefined?traits[i][0]+'（未圈選）':traits[i][3][state.poles[i]]}
function renderGrid(){const head=`<colgroup>${order.map(()=>'<col style="width:5.9%">').join('')}<col style="width:28%"><col style="width:7.1%"></colgroup><thead><tr>${order.map(j=>j===10?'<td>×</td>':`<td><select aria-label="工作 ${j+1} 喜好順序" data-rank="${j}">${options(10,state.ranks[j])}</select></td>`).join('')}<th class="empty" colspan="2">對工作喜好的順序<br>1 最喜歡 · 10 最不喜歡</th></tr><tr>${order.map(j=>`<th class="jobhead">${j===10?'<span style="writing-mode:vertical-rl">理想工作</span>':`<span class="category">${j<3?'喜歡':j<6?'不喜歡':'了解'} ${j<3?j+1:j<6?j-2:j-5}</span><textarea aria-label="${j<3?'喜歡':j<6?'不喜歡':'了解'}的工作 ${j+1}" data-job="${j}">${esc(state.jobs[j])}</textarea>`}</th>`).join('')}<th class="empty">工作特性<br><small>由第三步選單帶入</small></th><th class="empty">重要性<br>1–10</th></tr></thead>`;$('#matrix').innerHTML=head+'<tbody>'+Array.from({length:10},(_,r)=>{const i=state.selected[r],valid=i!==undefined&&state.poles[i]!==undefined;return `<tr>${order.map(j=>`<td><select aria-label="${i===undefined?'未選特性':esc(traitLabel(i))}：${j===10?'理想工作':esc(state.jobs[j]||'工作 '+(j+1))}" data-rate="${i??''}" data-col="${j}" ${valid?'':'disabled'}>${options(5,state.ratings[i]?.[j])}</select></td>`).join('')}<td class="trait">${i===undefined?'<small>請至第三步選擇</small>':esc(traitLabel(i))}</td><td><select data-importance="${i??''}" aria-label="${i===undefined?'未選特性':esc(traitLabel(i))}重要性順序" ${i===undefined?'disabled':''}>${options(10,state.importance[i])}</select></td></tr>`}).join('')+'</tbody>';gridStatus()}
function gridStatus(){const n=state.selected.reduce((sum,i)=>sum+Object.values(state.ratings[i]||{}).filter(Boolean).length,0);const rankDone=state.ranks.filter(Boolean).length;const importanceDone=state.selected.filter(i=>state.importance[i]).length;$('#gridstatus').textContent=`工作名稱 ${state.jobs.filter(x=>x.trim()).length}/10　喜好排序 ${rankDone}/10　重要性排序 ${importanceDone}/10　方格評分 ${n}/110`}
$('#matrix').addEventListener('input',e=>{const d=e.target.dataset,v=e.target.value;if(d.job!==undefined){state.jobs[+d.job]=v;save();gridStatus()}});
$('#matrix').addEventListener('change',e=>{const d=e.target.dataset,v=e.target.value;if(d.rank!==undefined){swapRank(state.ranks,+d.rank,v,[0,1,2,3,4,5,6,7,8,9]);renderGrid()}else if(d.importance!==undefined&&d.importance!==''){swapRank(state.importance,+d.importance,v,state.selected);renderGrid()}else if(d.rate!==undefined&&d.rate!==''){const i=+d.rate;state.ratings[i]??={};state.ratings[i][+d.col]=v}save();gridStatus();renderGuided()});
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>showStep(+b.dataset.step)));$('#backGrid').addEventListener('click',()=>{if(state.selected.length!==10||state.selected.some(i=>state.poles[i]===undefined)){$('#selectionNote').textContent='請先選滿十項，並圈選每一項偏好的特性。';return}showStep(1);startRatings()});
$('#print').addEventListener('click',()=>{renderGrid();window.print()});window.addEventListener('beforeprint',()=>{document.querySelectorAll('#questions textarea').forEach(t=>{t.style.height='auto';t.style.height=t.scrollHeight+'px'})});window.addEventListener('afterprint',()=>document.querySelectorAll('#questions textarea').forEach(t=>t.style.height=''));
let interviewPart=0, ratingPart=0, guideMode='jobs';
function swapRank(target,key,value,keys){const old=target[key]||'';if(value){const other=keys.find(k=>k!==key&&String(target[k])===String(value));if(other!==undefined)target[other]=old}target[key]=value}
function renderInterview(){document.querySelectorAll('.question-group').forEach((g,i)=>g.classList.toggle('inactive-part',i!==interviewPart));$('#interviewNav').innerHTML=groups.map(([t],i)=>`<button data-part="${i}" aria-pressed="${interviewPart===i}">${t}</button>`).join('');$('#interviewActions').innerHTML=`<span class="section-count">${interviewPart+1} / 5</span>${interviewPart>0?'<button id="prevPart">上一區塊</button>':''}<button class="primary" id="nextPart">${interviewPart===4?'下一步：生涯方格':'下一區塊：'+groups[interviewPart+1][0]}</button>`;$('#nextPart').onclick=()=>{if(interviewPart===4)showStep(1);else{interviewPart++;renderInterview();$('#interviewNav').scrollIntoView({block:'start',behavior:'smooth'});$('#questions .question-group:not(.inactive-part) textarea').focus({preventScroll:true})}};if($('#prevPart'))$('#prevPart').onclick=()=>{interviewPart--;renderInterview()};$('#interviewNav').querySelectorAll('button').forEach(b=>b.onclick=()=>{interviewPart=+b.dataset.part;renderInterview()})}
function renderGuided(){const ready=state.selected.length===10&&state.selected.every(i=>state.poles[i]!==undefined);$('#guided').innerHTML=`<div class="subnav"><button id="jobMode" aria-pressed="${guideMode==='jobs'}">填寫工作與喜好</button><button id="ratingMode" aria-pressed="${guideMode==='ratings'}">逐項評分</button></div><div id="guideContent"></div>`;$('#jobMode').onclick=()=>{guideMode='jobs';renderGuided()};$('#ratingMode').onclick=()=>{guideMode='ratings';renderGuided()};if(guideMode==='jobs'){renderJobs();return}if(!ready){$('#guideContent').innerHTML='<div class="empty-note"><p>先選好十項工作特性，就能開始逐項評分。</p><button class="primary" id="chooseTraits">前往第三步選擇想法</button></div>';$('#chooseTraits').onclick=()=>showStep(2);return}ratingPart=Math.min(ratingPart,state.selected.length-1);renderRating()}
function renderJobs(){$('#guideContent').innerHTML='<p class="smallhelp">工作名稱可以直接橫向輸入。喜好順序 1 是最喜歡、10 是最不喜歡；選到已有的名次時，會自動交換。</p>'+[['喜歡的工作',0,3],['不喜歡的工作',3,6],['您所瞭解的工作',6,10]].map(([title,a,b])=>`<fieldset class="job-group"><legend>${title}</legend>${Array.from({length:b-a},(_,n)=>{const j=a+n;return `<div class="job-line"><label><span>${n+1}.</span><input data-easyjob="${j}" aria-label="${title} ${n+1}" value="${esc(state.jobs[j])}" placeholder="填入工作名稱" autocomplete="off"></label><label class="rank-label">喜好順序<select data-easyrank="${j}" aria-label="${title} ${n+1} 喜好順序">${options(10,state.ranks[j])}</select></label></div>`}).join('')}</fieldset>`).join('')+'<div class="actions"><button class="primary" id="jobsNext">填好了，選擇我的想法</button></div>';$('#guideContent').querySelectorAll('[data-easyjob]').forEach(el=>{el.oninput=()=>{state.jobs[+el.dataset.easyjob]=el.value;save();gridStatus()};el.onchange=()=>renderGrid();el.onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();const next=$(`[data-easyjob="${+el.dataset.easyjob+1}"]`);if(next)next.focus();else $('#jobsNext').focus()}}});$('#guideContent').querySelectorAll('[data-easyrank]').forEach(el=>el.onchange=()=>{swapRank(state.ranks,+el.dataset.easyrank,el.value,[0,1,2,3,4,5,6,7,8,9]);$('#guideContent').querySelectorAll('[data-easyrank]').forEach(x=>x.value=state.ranks[+x.dataset.easyrank]||'');save();renderGrid()});$('#jobsNext').onclick=()=>showStep(2)}
const scoreNames=['非常不符合','不符合','有點符合又不太符合','符合','非常符合'];
function renderRating(){const i=state.selected[ratingPart],name=traitLabel(i);const n=Object.values(state.ratings[i]||{}).filter(Boolean).length;$('#guideContent').innerHTML=`<div class="rating-heading"><label>工作特性<select id="traitJump" aria-label="切換工作特性">${state.selected.map((k,r)=>`<option value="${r}" ${r===ratingPart?'selected':''}>${r+1}. ${esc(traitLabel(k))}</option>`).join('')}</select></label><label>重要性順序<select id="easyImportance" aria-label="${esc(name)}重要性順序">${options(10,state.importance[i])}</select></label></div><h2 class="current-trait">${esc(name)}</h2><p class="smallhelp">依照你的認識，這些工作有多符合「${esc(name)}」？重要性 1 為最重要；重複名次會自動交換。</p><div class="score-legend">${scoreNames.map((x,j)=>`<span><b>${j+1}</b> ${x}</span>`).join('')}</div><div class="rating-rows">${[10,0,1,2,3,4,5,6,7,8,9].map(j=>`<div class="rating-row" data-row="${j}"><span class="rating-job">${j===10?'理想工作':esc(state.jobs[j]||'工作 '+(j+1)+'（尚未命名）')}</span><div class="score-buttons" role="group" aria-label="${j===10?'理想工作':esc(state.jobs[j]||'工作 '+(j+1))}符合${esc(name)}的程度">${[1,2,3,4,5].map(v=>`<button data-score="${v}" data-jobscore="${j}" aria-pressed="${String(state.ratings[i]?.[j])===String(v)}" aria-label="${v}：${scoreNames[v-1]}">${v}</button>`).join('')}<button class="clear-score" data-clear="${j}" aria-label="清除此工作評分">清除</button></div></div>`).join('')}</div><div class="rating-bottom"><span id="ratingProgress" role="status">特性 ${ratingPart+1}/10 · 已評 ${n}/11</span><div>${ratingPart>0?'<button id="prevTrait">上一項</button>':''}<button class="primary" id="nextTrait">${ratingPart===9?'檢查完成狀況':'下一項特性'}</button></div></div><p id="completionMessage" role="status"></p>`;$('#traitJump').onchange=e=>{ratingPart=+e.target.value;renderRating()};$('#easyImportance').onchange=e=>{swapRank(state.importance,i,e.target.value,state.selected);save();renderGrid()};$('#guideContent').querySelectorAll('[data-score]').forEach(b=>b.onclick=()=>{const j=+b.dataset.jobscore;state.ratings[i]??={};state.ratings[i][j]=b.dataset.score;syncScore(i,j)});$('#guideContent').querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{const j=+b.dataset.clear;if(state.ratings[i])delete state.ratings[i][j];syncScore(i,j)});if($('#prevTrait'))$('#prevTrait').onclick=()=>{ratingPart--;renderRating();scrollRating()};$('#nextTrait').onclick=()=>{if(ratingPart<9){ratingPart++;renderRating();scrollRating()}else checkComplete()}}
function syncScore(i,j){document.querySelectorAll(`[data-jobscore="${j}"]`).forEach(b=>b.setAttribute('aria-pressed',String(state.ratings[i]?.[j])===b.dataset.score?'true':'false'));const n=Object.values(state.ratings[i]||{}).filter(Boolean).length;$('#ratingProgress').textContent=`特性 ${ratingPart+1}/10 · 已評 ${n}/11`;$('#completionMessage').textContent='';save();renderGrid()}
function scrollRating(){$('#guided').scrollIntoView({behavior:'smooth',block:'start'})}
function startRatings(){guideMode='ratings';const first=state.selected.findIndex(i=>Object.values(state.ratings[i]||{}).filter(Boolean).length<11||!state.importance[i]);ratingPart=Math.max(first,0);renderGuided();scrollRating()}
function checkComplete(){const unanswered=state.selected.findIndex(i=>Object.values(state.ratings[i]||{}).filter(Boolean).length<11||!state.importance[i]);if(unanswered>=0){$('#completionMessage').innerHTML='還有未完成的評分或重要性排序。 <button id="findMissing">前往第一個未完成項目</button>';$('#findMissing').onclick=()=>{ratingPart=unanswered;renderRating();scrollRating()};return}if(state.jobs.some(x=>!x.trim())||state.ranks.some(x=>!x)){$('#completionMessage').innerHTML='評分已完成；還有工作名稱或喜好順序未填。 <button id="finishJobs">補上工作資料</button>';$('#finishJobs').onclick=()=>{guideMode='jobs';renderGuided();scrollRating()};return}$('#completionMessage').textContent='生涯方格已填寫完成。你可以展開完整方格回看，或列印全部內容。';$('#fullGrid').open=true}
function setupSmooth(){$('#continueMenu').onclick=()=>$('#backGrid').click();const first=groups.findIndex((g,i)=>{const offset=groups.slice(0,i).reduce((s,x)=>s+x[1].length,0);return state.answers.slice(offset,offset+g[1].length).some(x=>!x.trim())});interviewPart=Math.max(first,0);renderInterview();let priorOpen=[];window.addEventListener('beforeprint',()=>{priorOpen=Array.from(document.querySelectorAll('details')).map(d=>[d,d.open]);priorOpen.forEach(([d])=>d.open=true)});window.addEventListener('afterprint',()=>priorOpen.forEach(([d,o])=>d.open=o));$('#questions').addEventListener('input',e=>{if(e.target.tagName==='TEXTAREA'){e.target.style.height='auto';e.target.style.height=Math.max(82,e.target.scrollHeight)+'px'}})}

setupSmooth();renderChoices();renderGrid();showStep(Number.isInteger(state.step)?state.step:0);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_career_step',description:'切換至自我訪談、生涯方格或我的想法選單，不更改填寫內容。',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:0,maximum:2}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.step)||input.step<0||input.step>2)throw Error('無效步驟');showStep(input.step);return {step:state.step}}})).catch(()=>{})}catch{}}
